[[coveio_abi]]
== Confidential VM Extension (CoVE) IO ABI

=== CoVE IO Host Extension

==== IOMMU Management

[#sbi_covh_register_iommu()]
===== IOMMU Registration (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_register_iommu(unsigned long iommu_id,
                                      unsigned long msi_cfg[3]);
-----

[#sbi_covh_notify_iommu_msi()]
===== IOMMU MSI notification (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_notify_iommu_msi(unsigned long iommu_id);
-----

==== Root Port Management

[#sbi_covh_register_rp()]
===== PCIe Root Port Registration (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_register_rp(unsigned long rp_id,
                                   unsigned long mmio_ranges);
-----

==== Physical Device Management

[#sbi_covh_connect_device()]
===== Device Connection (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_connect_device()(unsigned long device_id,
                                        unsigned long stream_id);
-----

Establishes a secure SPDM session between the TSM and a device identified by
`device_id`, and configure the PCIe IDE link between that device and its
upstream Root Port. The configured IDE link must use the selective IDE stream
identified by `stream_id`.

[#sbi_covh_disconnect_device()]
===== Device Disconnection (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_disconnect_device()(unsigned long device_id);
-----

==== TVM Memory Management

[#sbi_covh_add_tvm_device_region()]
===== Device Interface Memory Region Mapping into the TVM Address Space (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_add_tvm_interface_region(unsigned long tvm_id,
                                                unsigned long device_if_id,
                                                unsigned long base_addr,
                                                unsigned long num_pages);
-----

===== Device Interface Memory Region Reclaiming (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_reclaim_tvm_interface_region(unsigned long tvm_id,
                                                    unsigned long device_if_id,
                                                    unsigned long base_addr,
                                                    unsigned long num_pages);
-----

Reclaims a device interface MMIO region previously added to a TVM address space.
The host supervisor domain manager may call this function when the `tvm_id` TVM
stops `device_if_id` device interface, in order for the TSM to unmap the device
interface MMIO ranges from the TVM address space.

If `device_if_id` is still bound to `tvm_id` when this call is made, the TSM
unbinds the device interface from the TVM first.

==== Device Interface Management

[#sbi_covh_bind_interface()]
===== Device Interface Binding (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_bind_interface()(unsigned long tvm_id,
                                        unsigned long device_if_id);
-----

[#sbi_covh_unbind_interface()]
===== Device Interface Unbinding (FID TBD)
[source, C]
-----
struct sbiret sbi_covh_unbind_interface()(unsigned long tvm_id,
                                          unsigned long device_if_id);
-----

=== CoVE IO Guest Extension

==== Physical Device Query

[#sbi_covg_get_device_link()]
===== Device Link Status (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_device_link(unsigned long device_id);
-----

[#sbi_covg_get_device_certificate()]
===== Device Identity Certificate (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_device_certificate(unsigned long device_id);
-----

[#sbi_covg_get_device_measurements()]
===== Device Measurements (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_device_measurements(unsigned long device_id);
-----

[#sbi_covg_get_device_spdm_attrs()]
===== Device SPDM Session Attributes (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_device_spdm_attrs(unsigned long device_id);
-----

==== Device Interface Management

[#sbi_covg_get_interface_report()]
===== Device Interface TDISP Report (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_interface_report(unsigned long device_if_id);
-----

[#sbi_covg_get_interface_state()]
===== Device Interface State (FID TBD)
[source, C]
-----
struct sbiret sbi_covg_get_interface_state(unsigned long device_if_id);
-----

[#sbi_covg_map_interface_mmio()]
===== Device Interface MMIO Mapping (FID TBD)
[source, C]
----
struct sbiret sbi_covg_map_interface_mmio(unsigned long device_if_id
                                          unsigned long gpa,
                                          unsigned long hpa_offset,
                                          unsigned long size);
----

[#sbi_covg_start_interface()]
===== Start Device Interface (FID TBD)
[source, C]
----
struct sbiret sbi_covg_start_interface(unsigned long device_if_id);
----

[#sbi_covg_stop_interface()]
===== Stop Device Interface (FID TBD)
[source, C]
----
struct sbiret sbi_covg_stop_interface(unsigned long device_if_id);
----
