[[arch_overview]]
== Architectural Overview

CoVE-IO is made of multiple hardware and software components.

Figure 1 below illustrates the overall CoVE-IO architectural components and how
they interact together:

[[COVE_IO_ARCHITECTURE]]
.CoVE-IO High Level Architecture
image::images/cove-io-architecture.svg[align="center"]

The TEE Security Manager (TSM) orchestrates and manages TEE Virtual Machines
(TVM), as defined by the <<CoVE>> specification. The TSM operates in HS-Mode
and is the confidential Supervisor Domain manager. It uses the <<Smmtt>>
specified Memory Tracking Table (MTT) to enforce TVM memory isolation from
the host Supervisor Domain.

As the confidential Supervisor Domain manager, the TSM provides the `COVH` ABI
for the host OS/VMM to create and destroy TVMs, and donate or reclaim
confidential memory from them. TVMs can interact with the TSM through the
`COVG` ABI.

CoVE-IO extends both the `COVH` and `COVG` ABIs for bringing TEE-IO capable
devices into the trust boundary of TVMs. These extensions allow for configuring
and registering PCIe root ports and then binding physical devices interfaces
(TDI) and TVMs together.

With the CoVE-IO ABIs and flows, TDIs can access TVM confidential memory
directly through DMA. Based on the TVM configuration, the DMA accessible
confidential memory could be all TVM memory or a subset of the TVM memory. At
least one platform IOMMU instance must be exclusively tied to each supervisor
domains managing TVMs to which TDIs can be bound to. CoVE-IO uses the Smmtt MTT
and I/O MTT extensions, together with the IOMMU instance memory-mapped register
programming interface (`RPI` in figure 1) to grant TDIs with direct access to
their bound TVM confidential memory and isolate it from DMA originating from any
unbound TDI.

With the CoVE-IO model, the TVM ultimately holds the decision to accept or
reject a bound TDI into or from its TCB. Access to a TVM confidential memory
from a TDI is disabled until a TVM notifies the TSM that it trusts the TDI and
its configuration. The TVM communicates this decision after verifying the TDI,
which generally includes attesting to the physical device the TDI belongs to.
The device attestation process is specific to each TVM workload configuration,
but it may be handled by the Trusted Device Manager (TDM).

To ensure the confidentiality and integrity of TVM data, PCIe IDE streams are
established between the PCIe Root Port and its bound TDI. Under the CoVE-IO
framework, the TSM is responsible for generating and configuring the necessary
IDE keys. Specifically, the TSM configures the PCIe physical device using the
PCIe IDE Key Management (`IDE_KM`) protocol. However, because PCIe Root Port key
management is platform-specific, the TSM delegates those operations to the
platform's RDSM.
