[[attestation]]
== Device Attestation

There are two attestation stages involved in the CoVE-IO architecture.

- TVM attests the device
- A third party attests the TVM with the device

The IETF RATS Remote Attestation Architecture <<RATS>> can be applied to both.

.Remote Attestation Framework (IETF RATS)
image::images/rats-arch.svg[align="center"]

=== TVM attesting the Device

The TVM must verify and trust the device before offloading the workload to the
TDI. According to the <<TDISP>> architecture, the high level steps for that
stage are as follows:

1. The TSM collects the device certificate and measurement from the DSM as the
   evidence, via SPDM protocol.
2. The TSM presents the evidence to the TVM.
3. A TVM verifier appraises the evidence and produce the attestation result to
   the relying party in the TVM, such as device driver.
4. The local relying part running in the TVM accepts (or rejects) the device
   into (from) its TCB.

The above process follows the background-check model, as defined by <<RATS>>.
The <<RATS>> passport model is not supported by the CoVE-IO attestation
architecture, because it adds complexity to the TSM as the TSM would need to
perform the verification and pass the attestation result to TVM.
Since the TSM is in the TVM's TCB, its attack surface should be kept minimal.

In step 3, the verifier needs to perform the verification for the device. There
are two possible use cases:

==== Local Verification
With local verification, the endorsement and reference values are provisioned
into the TVM. 
  
Static provisioning means the data is built into the TVM image at build time,
while dynamic provisioning means the data is provisioned into the TVM at runtime.

The endorsement may include the device root CA certificate and its associated
certificate revocation list (CRL). The reference value includes the reference
integrity manifest (RIM), also known as golden measurement.

When running locally, the verifier in the TVM validates the device certificate
according to the device root CA certificate and CRL, and then compares the
device measurement with the measurement from its locally provisioned RIM.

The TVM may have a local policy update mechanism to update the endorsement and
reference value. How to trigger the update is out of scope of this specification.
It could be a pull model, such as TVM querying for updates periodically. Or it
could be a push mode, such as orchestrator posting the update when it notices
the device vendor update. To maintain the integrity of the policy update, the
update package should have protection mechanism, such as digital signature.

==== Remote Verification
When the device is verified remotely, the endorsement and reference values
are not provisioned into the TVM, but are accessible from an externally
available service, also known as a relying party for the device.

The verifier itself can either run locally or be hosted on a remote service
as well, typically available through an HTTPS-based protocol.
It always collects the up-to-date endorsement and RIM from the device relying party.

.Device Attestation Comparison
[width=90%, align="center", options="header"]
|===
| Use Case                        | Local Verification                     | Remote Verification
| Endorsement (Root CA Cert, CRL) | Provisioned in TVM (Static or Dynamic) | Remote Service
| Reference Value (RIM)           | Provisioned in TVM (Static or Dynamic) | Remote Service
| Policy Update (Endorsement, Reference) | No update or scheduled update (Pull or Push) | Always up-to-date
| Verifier Location               | Inside of TVM         | Inside of TVM or Remote Service
|===

==== Device Runtime Update and Reattestation

A TEE-IO device may support runtime update. Currently, there are two policy
settings controlling device runtime update.

===== SPDM Session `TerminationPolicy`

This SPDM session attribute controls if runtime update will cause SPDM session
termination or device may keep the session.

> **Note**
> The session termination means the IDE stream will change to `insecure` state
> and TDI in `ERROR` state.

The SPDM `TerminationPolicy` is set in SPDM `KEY_EXCHANGE` message by
TSM. The TSM should return such policy information to the TVM via
`sbi_covg_get_device_spdm_attrs()` `COVG` ABI.

===== TDISP `NO_FW_UPDATE`

This TDISP interface attribute controls if runtime update is allowed after TDI
in either `CONFIG_LOCKED` or `RUN` state.

> **Note**
> Runtime update is always allowed if TDI is in `CONFIG_UNLOCKED` or `ERROR`.

The TDISP `NO_FW_UPDATE` is set in TDISP `LOCK_INTERFACE_REPORT` message by TSM,
and is returned in BIT0 of `INTERFACE_INFO` in `TDI Report Structure` by
the device. The TVM can get the full `TDI Report Structure` via
the `sbi_covg_get_interface_report()` `COVG` ABI.

---

The TVM should consult both setting to decide if it can accept the device
runtime update.

If the TVM allows the device runtime update after lock (`NO_FW_UPDATE`=0) and
update without session termination (`TerminationPolicy`=1), then the TVM may
want to do attestation again to verify the device.

There are 2 possible models.

===== Post-update reattestation

After the device performs the update, the TVM will collect both the certificate
and the measurement and do verification again to determine if it still wants to
accept the device. If the TVM decides to no longer accept the device any more,
the TVM will use `sbi_covg_stop_interface()` ABI to request the VMM to use
`sbi_covh_unbind_interface()` to unbind the TDI, then the TVM will verify with
TSM if the TDI is really unbound by the VMM.

How the device performs the update is out of scope of this specification.
It could be initiated by current TVM, other TVMs, other legacy VMs, VMM, or even
out of band (OOB) mechanism, such as Baseboard Management Controller (BMC).

When the TVM performs the reattestation is also out of scope of this
specification. It could be a pull mode with policy inside of TVM, such as
reattestation every week. Or it could be an interrupt mode such as request
triggered by the orchestrator.

> **Note**
> In this mode, the device can be updated before the TVM performs the
reattestation, or just after TVM performs reattestation. If this is a
concern, the TVM should choose no-update or pre-update attestation.

===== Pre-update attestation

With post-update reattestation, there is a gap between update time and
attestation time. Confidential data access from the TDI may happen before the
updated device is re-attested and re-accepted by the TVM.

SPDM 1.3 added an optional event mechanism and `MeasurementPreUpdate` event
notification. If the device, TSM, and TVM all support SPDM 1.3, the TVM may get
the `MeasurementPreUpdate` event notification and verify the measurement before
the update takes effect. If the TVM cannot accept the new measurement, then the
TVM can unbind the TDI before runtime update.

The difference between this pre-update attestation and post-update reattestation
is that the update takes effect when the verification happens.
Pre-update attestation gives a chance to unbind TDI before runtime update,
while post-update reattestation can only unbind TDI after runtime update. That
can remove the gap between update time and attestation time.

> **Note**
> In this mode, the device will be updated, regardless of the TSM or the TVM
accepting the firmware update or not. If TSM cannot accept the new firmware,
the TSM shall terminate the SPDM session with SPDM message `END_SESSION`,
but not acknowledge the SPDM event with SPDM message `EVENT_ACK`.
If TVM cannot accept the new firmware, the TVM shall unbind the TDI.

=== Third party attesting the TVM with the device

The third party must follow the CoVE defined attestation mechanism to perform
local or remote attestation and verify the TVM.

The CoVE-IO architecture adds the additional device related information to the
TVM attestation evidence, in order to allow the third party to verify the
attached device TDI.

Depending on the verification process being local or remote, the TVM needs to
add different pieces of device-related information to the TVM report:

==== Local Verification

The TVM report should include the device verifier code, the device policy,
including the provisioned device root CA certificate, CRL, and RIM.

If the TVM supports device policy update, then the secure signed update
mechanism should be implemented. In that case, the signer of the update data
shall be included in the TVM report as the trust anchor.

The device measurement and certificate are not required in the TVM report,
however the TVM should provide a mechanism to return the device measurement
and certificate to the verifier for further verification.

==== Remote Verification

The TVM report should include measurements of either the device verifier or
the proxy connecting to the verifier service. It should also include the remote
service URL and the public certificate as the trust anchor.

The detailed, up-to-date endorsement or reference value is *not* required to be
part of the TVM report. 

Although the device measurement and certificate are not required to be included
in the TVM report, the TVM should provide a mechanism to return the device
measurement and certificate for the verifier to perform further verification.

.TVM Attestation Comparison
[width=90%, align="center", options="header"]
|===
| Use Case                           | Local Verification                 | Remote Verification
| Device Verifier Code in TVM report | TVM Verifier                       | TVM Verifier or Stub Function to Verifier Service
| Device Policy Data in TVM report   | Endorsement and Reference Value    | Remote Service URL and Public Cert (trust anchor)
| Device Policy Update in TVM report | Signer of Update (as trust anchor) | N/A
| Device identity NOT in TVM report  | Device Measurement and Certifcate  | Device Measurement and Certifcate
|===

