[[coveio_abi]]
== Confidential VM Extension (CoVE) IO ABI

=== CoVE IO Function IDs Namespace

As a <<CoVE>> SBI extension, CoVE-IO has a reserved CoVE Function ID (FID)
namespace. For all three CoVE EID (`COVH`, `COVI` and `COVG`), the CoVE-IO FIDs
must be in the `[1024:1087]` range.

=== CoVE IO Host Extension (EID #0x434F5648 "COVH")

==== IOMMU Management

[#sbi_covh_register_iommu()]
===== Function: CoVE Host Register IOMMU (FID #1024)
[source, C]
-----
struct sbiret sbi_covh_register_iommu(unsigned long iommu_id,
                                      unsigned long msi_cfg[3]);
-----

Registers an IOMMU (`iommu_id`) with a TSM. The `msi_cfg` MSI vectors are
allocated by the host supervisor domain manager (e.g. the host VMM).

The TSM configures the IOMMU TSM supervisor domain programming interface
`s_msi_cfg_table` with the provided MSI vectors.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_register_iommu]
.CoVE Host Register IOMMU
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | The `iommu_id` index is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_notify_iommu_msi]
===== Function: CoVE Host Notify IOMMU MSI (FID #1025)
[source, C]
-----
struct sbiret sbi_covh_notify_iommu_msi(unsigned long iommu_id);
-----

Notifies the TSM about a pending MSI for the TSM supervisor domain.

When servicing this request, the TSM must first verify that there are pending
MSIs, by reading the IOMMU `s_ipsr` register from the IOMMU TSM security
domain programming interface. If there are some, it handles the interrupts as
needed.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_notify_iommu_msi]
.CoVE Host Notify IOMMU MSI
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | The `iommu_id` index is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

==== PCIe Root Port Management

[#sbi_covh_register_rp]
===== Function: CoVE Host Register PCIe Root Port (FID #1026)
[source, C]
-----
struct sbiret sbi_covh_register_rp(unsigned long rp_id,
                                   unsigned long mmio_ranges);
-----

Registers a PCIe Root Port (RP) for TEE I/O and IDE ownership with the TSM.

This function associates a RP id to its MMIO space (for configuring the RP IDE
capability) and all the MMIO ranges that are routed through it.

The TSM must compare these 2 arguments with the information it received from
the platform ROT through the TEE I/O manifest. If both match, it can proceed
into establishing an SPDM session with the RP.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_register_rp]
.CoVE Host Register PCIe Root Port
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | The `rp_id` index is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

==== Physical Device Management

[#sbi_covh_connect_device]
===== Function: CoVE Host Connect Device (FID #1027)
[source, C]
-----
struct sbiret sbi_covh_connect_device()(unsigned long device_id,
                                        unsigned long stream_id,
                                        unsigned long connection_data_addr_out,
                                        unsigned long connection_data_size);
-----

Establishes a secure SPDM session between the TSM and a device identified by
`device_id`, and configure the PCIe IDE link between that device and its
upstream Root Port. The configured IDE link must use the selective IDE stream
identified by `stream_id`.

The TSM returns the device connection transcript data to the host Supervisor Domain
manager at `connection_data_addr_out`, structured as follows:

[#table_sbi_covh_connection_transcript]
.CoVE Device Connection Transcript
[options=header]
|===
| *Byte Offset* | *Field*                    | *Size (bytes)*               | *Description*
| 0             | COVEIOVersion              | 1                            | CoVE-IO version
| 1             | ConnectionTranscriptLength | 4                            | Size of the `ConnectionTranscript` field that follows, in bytes
| 5             | ConnectionTranscript       | `ConnectionTranscriptLength` | Device connection transcript
|===

`connection_data_addr_out` must be 4KB-aligned and points to a memory region
that is accessible to both the host Supervisor Domain manager and the TSM.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_connect_device]
.CoVE Host Connect Device
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | The `device_id` index is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_disconnect_device]
===== Function: CoVE Host Disconnect Device (FID #1028)
[source, C]
-----
struct sbiret sbi_covh_disconnect_device()(unsigned long device_id);
-----

Disconnects the TSM from the device identified by `device_id`.

The TSM must first stop all TVM-bound interfaces belonging to `device_id`, clear
the IDE link and keys for `device_id` and then terminate the secure SPDM session
established with `device_id`.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_disconnect_device]
.CoVE Host Disconnect Device
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | The `device_id` index is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

==== TVM Memory Management

[#sbi_covh_add_tvm_interface_region]
===== Function: CoVE Host Add TVM Interface Region (FID #1029)
[source, C]
-----
struct sbiret sbi_covh_add_tvm_interface_region(unsigned long tvm_id,
                                                unsigned long device_if_id,
                                                unsigned long base_addr,
                                                unsigned long region_len);
-----

Adds a device interface MMIO region into a TVM address space.

The host supervisor domain manager must call this function for all
`device_if_id` MMIO regions before binding it to `tvm_id`. This function returns
an error if `device_if_id` is already bound to `tvm_id`.

The TSM creates uncacheable G-stage mappings for the added region, so that the
TVM outbound transaction will not trigger MMIO page faults. The TSM must not
enable the created mappings until the TVM accepts the TDI in its TCB.

The possible error codes returned in `sbiret.error` are shown below.

`base_addr` value must be 4KB-aligned.

`region_len` value must be 4KB-aligned.

[#table_sbi_covh_add_tvm_interface_region]
.CoVE Host Add TVM Interface Region
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

===== Function: CoVE Host Reclaim TVM Interface Region (FID #1030)
[source, C]
-----
struct sbiret sbi_covh_reclaim_tvm_interface_region(unsigned long tvm_id,
                                                    unsigned long device_if_id,
                                                    unsigned long base_addr,
                                                    unsigned long region_len);
-----

Reclaims a device interface MMIO region previously added to a TVM address space.

The host supervisor domain manager may call this function when the `tvm_id` TVM
stops the `device_if_id` device interface, in order for the TSM to unmap the
device interface MMIO ranges from the TVM address space.

If `device_if_id` is still bound to `tvm_id` when this call is made, the TSM
unbinds the device interface from the TVM first.

The possible error codes returned in `sbiret.error` are shown below.

`base_addr` value must be 4KB-aligned.

`region_len` value must be 4KB-aligned.

[#table_sbi_covh_reclaim_tvm_device_region]
.CoVE Host Reclaim TVM Interface Region
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

==== Device Interface Management

[#sbi_covh_bind_interface]
===== Function: CoVE Host Bind Interface (FID #1031)
[source, C]
-----
struct sbiret sbi_covh_bind_interface()(unsigned long tvm_id,
                                        unsigned long device_if_id);
-----

Binds a TVM and a device interface together.

The TSM returns an error if a secured SPDM session is not established with the
DSM or if a stream IDE link is not set up.

After this calls completes successfully, the `device_id_interface` is in the
TDISP `CONFIG_LOCKED` state.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_bind_interface]
.CoVE Host Bind Interface
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_unbind_interface]
===== Function: CoVE Host Unbind Interface (FID #1032)
[source, C]
-----
struct sbiret sbi_covh_unbind_interface()(unsigned long tvm_id,
                                          unsigned long device_if_id);
-----

Unbinds a device interface from a TVM.

After this calls completes successfully, the `device_id_interface` is moved
back to the TDISP `CONFIG_UNLOCKED` state, from one of the `CONFIG_LOCKED`,
`CONFIG_UNLOCKED` or `CONFIG_ERROR` states.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_unbind_interface]
.CoVE Host Unbind Interface
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_spdm_key_update]
===== Function: CoVE Host SPDM Key Update (FID #1033)
[source, C]
-----
struct sbiret sbi_covh_spdm_key_update(unsigned long device_id);
-----

Perform an SPDM key update for a SPDM connection between the TSM and
a connected device.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_spdm_key_update]
.CoVE Host SPDM Key Update
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_ide_key_refresh]
===== Function: CoVE Host IDE Key Refresh (FID #1034)
[source, C]
-----
struct sbiret sbi_covh_ide_key_refresh(unsigned long device_id,
                                       unsigned long stream_id);
-----

Perform an IDE key refresh for a connected device IDE stream.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_ide_key_refresh]
.CoVE Host IDE Key Refresh
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_spdm_heartbeat]
===== Function: CoVE Host SPDM Heartbeat (FID #1035)
[source, C]
-----
struct sbiret sbi_covh_spdm_heartbeat(unsigned long device_id);
-----

Perform an SPDM session heartbeat for a SPDM connection between the TSM and
a connected device.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_spdm_heartbeat]
.CoVE Host SPDM Heartbeat
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covh_spdm_data]
===== Function: CoVE Host Device Connection Transcript (FID #1036)
[source, C]
-----
struct sbiret sbi_covh_get_device_connection_transcript(unsigned long device_id,
                                                        unsigned long transcript_data_addr_out,
                                                        unsigned long transcript_data_size);
-----

Pass the device connection transcript data back to the TSM for a given connected
device. The data is formatted according to the
[Device Connection Transcript](#function-cove-host-connect-device-fid-1027)
structure.

`transcript_data_addr_out` must be 4KB-aligned and points to a memory region
that is accessible to both the host Supervisor Domain manager and the TSM.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covh_get_device_connection_transcript]
.CoVE Device Connection Transcript
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | Invalid parameter value provided for `device_id`.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===


=== CoVE IO Guest Extension (EID #0x434F5647 "COVG")

==== Physical Device Query

[#sbi_covg_get_device_link]
===== Function: CoVE Guest Get Device Link (FID #1024)
[source, C]
-----
struct sbiret sbi_covg_get_device_link(unsigned long device_if_id);
-----

Gets the status of the link between the physical device hosting `device_if_id`
and the TVM. This covers both the SPDM and IDE links.

Returns the a link status bitmap through `sbiret.value`.

[source, C]
-------
// A secure SPDM Session is established.
#define SECURED_SPDM (1 << 0)

// A PCIe IDE link is established.
#define PCIE_IDE (1 << 1)
-------

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_get_device_link]
.CoVE Guest Get Device Link
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_get_device_connection_transcript]
===== Function: CoVE Guest Get Device Connection Transcript (FID #1025)
[source, C]
-----
struct sbiret sbi_covg_get_device_connection_transcript(unsigned long device_if_id,
                                                        unsigned long transcript_element_id,
                                                        unsigned long transcript_element_parameter,
                                                        unsigned long data_addr_out,
                                                        unsigned long data_size);
-----

Get a specific element from the device connection transcript, or the whole
transcript.

The `transcript_element_id` specifies which part of the device connection
transcript the TVM is requesting. It must be one of the following values:

[source, C]
-----
enum sbi_covg_transcript_element {
     /* Full device connection transcript */
     FULL_TRANSCRIPT = 0,

     /*
      * Reconstructed certificate chain for the physical device hosting
      * `device_if_id`, from the transcript `CERTIFICATE` SPDM responses.
      * The TSM returns the certificate chain in the form of the <<SPDM>>
      * defined `certificate chain format`.
      * The `transcript_element_parameter` is set to a certificate chain slot
      * ID and thus must be between 0 and 7 inclusive.
      */
     DEVICE_CERTIFICATE = 1,

     /*
      * SPDM measurement messages for the physical device hosting
      * `device_if_id`.
      * This is the concatenation of all `{GET_MEASUREMENTS, MEASUREMENTS}`
      * pairs that are exchanged between the SPDM measurement requester and the
      * responder. Only the last `MEASUREMENTS` shall include the digital
      * signature of the measurement transcript.
      */
     DEVICE_MEASUREMENT = 2,

     /*
      * SPDM `VCA` (Version-Capabilities-Algorithms) for the physical device
      * hosting `device_if_id`.
      * This is the concatenation of the `GET_VERSION`, `VERSION`,
      * `GET_CAPABILITIES`, `CAPABILITIES`, `NEGOTIATE_ALGORITHMS` and
      * `ALGORITHMS` SPDM messages from the transcript.
      */
     VCA = 3,

     /*
      * SPDM session messages for the physical device hosting
      * `device_if_id`.
      * This is the concatenation of the `KEY_EXCHANGE`, `KEY_EXCHANGE_RSP`,
      * `FINISH`, `FINISH_RSP` SPDM messages from the transcript.
      * It includes the `TerminationPolicy`, and `HeartbeatPeriod` etc.
      */
     SESSION = 4,

     /*
      * TDISP messages for the physical device hosting
      * `device_if_id`.
      * This is the concatenation of the `TDISP_GET_VERSION`, `TDISP_VERSION`,
      * `TDISP_GET_CAPABILITIES` and `TDISP_CAPABILITIES` TDISP messages from
      * the trasncript.
      * It includes the `TSM_CAPS`, `DSM_CAPS`, `REQ_MSGS_SUPPORTED`, and
      * `LOCK_INTERFACE_FLAGS_SUPPORTED`, etc.
      */
     TDISP_VC = 5,
}
-----

`data_addr_out` must be 4KB-aligned.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_get_device_connection_transcript]
.CoVE Guest Get Device Connection Transcript
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAMS  | Invalid parameter value provided for `device_if_id` or `transcript_element_id`.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_get_device_measurements]
===== Function: CoVE Guest Get Device Measurements (FID #1026)
[source, C]
-----
struct sbiret sbi_covg_get_device_measurements(unsigned long device_if_id,
                                                        unsigned long nonce_addr,
                                                        unsigned long msmt_req_attr,
                                                        unsigned long msmt_addr_out,
                                                        unsigned long msmt_size);
-----

Gets the measurements of the physical device hosting `device_if_id`.

The TVM can call this interface multiple times to get the latest device measurement.

The TSM returns the measurements in the form of the complete, signed <<SPDM>>
measurement transcript, including `VCA` and all `{GET_MEASUREMENTS, MEASUREMENTS}`
pairs that are exchanged between the SPDM measurement requester and the
responder. Only the last `MEASUREMENTS` shall include the digital signature of
the measurement transcript.

The `nonce_addr` parameter points at an optional 32 bytes long buffer holding a
cryptographic nonce.

For any non zero value, the nonce is used as the SPDM `GET_MEASUREMENTS` request
`Nonce` field. When set to `0x0`, the TSM ignores this argument and generates a
nonce on behalf of the TVM.

`msmt_req_attr` is used as the measurement request attributes in SPDM
`GET_MEASUREMENT` request `param1` field. Only `RawBitStreamRequested` bit is
valid and the rest bits are igored. The last `GET_MEASUREMENT` request must
set `SignatureRequested` bit to request the digital signaure of the measurement
transcript.

Both `msmt_addr_out` and `nonce_addr` must be 4KB-aligned.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_get_device_measurements]
.CoVE Guest Get Device Measurements
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

==== Device Interface Management

[#sbi_covg_get_interface_report]
===== Function: CoVE Guest Get Interface Report (FID #1027)
[source, C]
-----
struct sbiret sbi_covg_get_interface_report(unsigned long device_if_id
                                                        unsigned long if_report_out,
                                                        unsigned long if_report_size);
-----

Gets the TDISP interface report for the device interface.

The TSM returns the interface report, as defined by the <<TDISP>> TDI Report
Structure, at the `if_report_out` address.

`if_report_out` must be 4KB-aligned.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_get_interface_report]
.CoVE Guest Get Interface Report
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_get_interface_state]
===== Function: CoVE Guest Get Interface State (FID #1028)
[source, C]
-----
struct sbiret sbi_covg_get_interface_state(unsigned long device_if_id);
-----

Gets the TDISP state for the device interface.

The TVM calls this function to verify that a bound device interface is in the
TDISP `RUN` state.

Returns the interface state through `sbiret.value`.

[source, C]
-------

enum sbi_covg_interface_state {
     /* TDISP CONFIG_UNLOCKED */
     Unlocked,

     /* TDISP CONFIG_LOCKED */
     Locked,

     /* TDISP RUN */
     Running,

     /* TDISP ERROR */
     Error,
};

-------

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_get_interface_state]
.CoVE Guest Get Interface State
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_map_interface_mmio]
===== Function: CoVE Guest Map Interface MMIO (FID #1029)
[source, C]
----
struct sbiret sbi_covg_map_interface_mmio(unsigned long device_if_id
                                          unsigned long gpa_addr,
                                          unsigned long hpa_addr,
                                          unsigned long size);
----

Maps a TVM MMIO region (from `gpa_address`, `size` bytes long) to a
`TDISP`-reported physical region (`hpa_addr`).

The TVM uses that function to verify from the TSM that all the device interface
MMIO regions exposed by the host supervisor domain manager are correctly mapped to
the trusted `TDISP`-reported MMIO regions. The TSM will enable those mappings
if the TVM calls the starts the device interface through the
`sbi_covg_start_interface` function.

All of `gpa_addr`, `hpa_addr` and `size` values must be 4KB-aligned.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_map_interface_mmio]
.CoVE Guest Map Interface MMIO
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_start_interface]
===== Function: CoVE Guest Start Interface (FID #1030)
[source, C]
----
struct sbiret sbi_covg_start_interface(unsigned long device_if_id);
----

Starts a bound device interface.

The TVM calls this function in order to accept a bound device interface into its
TCB. While servicing this request, the TSM moves the device interface TDISP
state from `CONFIG_LOCKED` to `RUN`.

After this calls completes successfully, the device interface I/O is ready and
available for the bound TVM.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_start_interface]
.CoVE Guest Start Interface
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_ALREADY_STARTED | The device interface is already started.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covg_stop_interface]
===== Function: CoVE Guest Stop Interface (FID #1031)
[source, C]
----
struct sbiret sbi_covg_stop_interface(unsigned long device_if_id);
----

Stops a bound device interface.

The TVM calls this function for either removing a bound device interface from
its TCB or initially rejecting it.

After this calls completes successfully, the device interface and the TVM are
no longer bound together.

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covg_stop_interface]
.CoVE Guest Stop Interface
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_ALREADY_STOPPED | The device interface is already stopped.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

=== CoVE IO TSM Extension (EID #0x434F5654 "COVT")

==== PCIe Root Port IDE Management

[#sbi_covt_program_rp_ide_key]
===== Function: CoVE TSM Program PCIe Root Port IDE Key (FID #1024)
[source, C]
-----
struct sbiret sbi_covt_program_rp_ide_key(unsigned long rp_id,
                                          unsigned long key_desc,
                                          unsigned long key_data_addr);
-----

Programs a PCIe IDE key into the `rp_id` PCIe Root Port. This is functionally
equivalent to the PCIe IDE KM `KEY_PROG` command.

The `key_desc` IDE key descriptor must be structured as follows:

[#table_sbi_covt_rp_ide_key_desc]
.CoVE IDE Key Descriptor
[options=header]
|===
| *Byte Offset* | *Field*       | *Size (bytes)* | *Description*
| 00h           | Stream_ID     | 1               | IDE selective stream ID
| 01h           | Sub_Stream_ID | 1               | IDE sub-stream ID
| 02h           | Key_Set       | 1               | IDE Key set. This must be 0 or 1, all other values are invalid.
| 03h           | Tx_Rx         | 1               | Transmitter key (0) or receiver key (1). All other values are invalid.
|===

The IDE key and IV data at `key_data_addr` must follow the same byte order and
structure as the `KEY_PROG` data object payload, as described in the
`IDE Key Management (IDE_KM)` section of the PCIe specification:

```title="CoVE IDE Key and IV"
 31            24 23           16 15            8 7              0
 ┌───────────────┬───────────────┬───────────────┬───────────────┐
 │ KEY_DW7_Byte3 │ KEY_DW7_Byte2 │ KEY_DW7_Byte1 │ KEY_DW7_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW6_Byte3 │ KEY_DW6_Byte2 │ KEY_DW6_Byte1 │ KEY_DW6_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW5_Byte3 │ KEY_DW5_Byte2 │ KEY_DW5_Byte1 │ KEY_DW5_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW4_Byte3 │ KEY_DW4_Byte2 │ KEY_DW4_Byte1 │ KEY_DW4_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW3_Byte3 │ KEY_DW3_Byte2 │ KEY_DW3_Byte1 │ KEY_DW3_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW2_Byte3 │ KEY_DW2_Byte2 │ KEY_DW2_Byte1 │ KEY_DW2_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW1_Byte3 │ KEY_DW1_Byte2 │ KEY_DW1_Byte1 │ KEY_DW1_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ KEY_DW0_Byte3 │ KEY_DW0_Byte2 │ KEY_DW0_Byte1 │ KEY_DW0_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ IFV_DW1_Byte3 │ IFV_DW1_Byte2 │ IFV_DW1_Byte1 │ IFV_DW1_Byte0 │
 ├───────────────┼───────────────┼───────────────┼───────────────┤
 │ IFV_DW0_Byte3 │ IFV_DW0_Byte2 │ IFV_DW0_Byte1 │ IFV_DW0_Byte0 │
 └───────────────┴───────────────┴───────────────┴───────────────┘
```

The initial state of a successfully programmed key is the `Programmed` state.

Calling `sbi_covt_program_rp_ide_key()` on a key that is in the `Programmed`
state overwrites the existing key content.

Overwriting a key that is in the `Enabled` state (i.e. enabled through the
`sbi_covt_set_go_rp_ide_key()` function) returns an `SBI_INVALID_STATE` error.

[#table_sbi_covt_program_rp_ide_key]
.CoVE TSM Program PCIe Root Port IDE Key
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_ADDRESS | `key_data_addr` is invalid.
| SBI_ERR_INVALID_PARAM   | `key_desc` or `rp_id` is invalid.
                            The key descriptor can be invalid if the stream ID
                            is unknown or the sub-stream ID is invalid.
| SBI_ERR_INVALID_STATE   | The key is in the `Enabled` state and can not be
                            programmed.
| SBI_ERR_IO              | The key can not be transferred or stored.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covt_clear_rp_ide_key]
===== Function: CoVE TSM Clear PCIe Root Port IDE Key (FID #1025)
[source, C]
-----
struct sbiret sbi_covt_clear_rp_ide_key(unsigned long rp_id,
                                        unsigned long stream_id);
-----

Clears all previously programmed IDE key for `stream_id` in the `rp_id` PCIe
Root Port.

If any `stream_id` bound IDE key is in the `Enabled` state (i.e. enabled through
the `sbi_covt_set_go_rp_ide_key()` function), this function returns an
`SBI_INVALID_STATE` error.

Once cleared from a Root Port, a key is no longer tracked by the RDSM and
its status is `Unknown`.

[#table_sbi_covt_clear_rp_ide_key]
.CoVE TSM Clear PCIe Root Port IDE Key
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAM   | `rp_id` or `stream_id` is invalid.
| SBI_ERR_INVALID_STATE   | At least one `stream_id` key is not in the
                           `Programmed` state.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===


[#sbi_covt_set_go_rp_ide_key]
===== Function: CoVE TSM Enable PCIe Root Port IDE Key (FID #1026)
[source, C]
-----
struct sbiret sbi_covt_set_go_rp_ide_key(unsigned long rp_id,
                                         unsigned long key_desc);
-----

Enables a previously programmed IDE key for the `rp_id` PCIe Root Port. This
is functionally equivalent to the PCIe IDE KM `K_SET_GO` command.

Once enabled, a key status moves to the `Enabled` state.

If the enabled key is a transmitter key, the `rp_id` Root Port will use the key
content to encrypt transmitted PCIe TLPs for the corresponding stream and
sub-streams combination.

If the enabled key is a receiver key, the `rp_id` Root Port prepares for
receiving and decrypting PCIe TLPs on the the corresponding stream and
sub-streams combination.

Once enabled, a key can not be cleared or reprogrammed. It must be
disabled first.

[#table_sbi_covt_set_go_rp_ide_key]
.CoVE TSM Enable PCIe Root Port IDE Key
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAM   | `key_desc` or `rp_id` is invalid.
| SBI_ERR_INVALID_STATE   | The key is not in the `Programmed` state and can not
                            be enabled.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===

[#sbi_covt_set_stop_rp_ide_key]
===== Function: CoVE TSM Disable PCIe Root Port IDE Tx Key (FID #1027)
[source, C]
-----
struct sbiret sbi_covt_set_stop_rp_ide_key(unsigned long rp_id,
                                           unsigned long key_desc);
-----

Disables a previously enabled IDE key for the `rp_id` PCIe Root Port. This
is functionally equivalent to the PCIe IDE KM `K_SET_STOP` command.

Once disabled, a key status moves back to the `Programmed` state.

[#table_sbi_covt_set_stop_rp_ide_key]
.CoVE TSM Disable PCIe Root Port IDE Key
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAM   | `key_desc` or `rp_id` is invalid.
| SBI_ERR_INVALID_STATE   | The key is not in the `Enabled` state and can not
                            be disabled.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===


[#sbi_covt_rp_ide_key_status]
===== Function: CoVE TSM PCIe Root Port IDE Key Status (FID #1028)
[source, C]
-----
struct sbiret sbi_covt_rp_ide_key_status(unsigned long rp_id,
                                         unsigned long key_desc);
-----

Gets the status of a PCIe Root Port IDE key.

Returns the key status through `sbiret.value`.

A key status must be one of the following values:

[source, C]
-------

enum sbi_covt_ide_key_status {
     /* The key is not programmed in the Root Port */
     Cleared,

     /* The key is programmed but it is not enabled */
     Programmed,

     /* The key is programmed and enabled */
     Enabled,
};

-------

When a selective IDE Stream State Machine transitions to the `Insecure` state
from the `Secure` one, all associated keys for that stream move to the `Cleared`
state:

[source,mermaid]
....
%%{init: {'theme': 'neutral', 'themeVariables': {'darkMode': true}, "flowchart" : { "curve" : "basis" } } }%%
stateDiagram-v2
    [*] --> Cleared

    Cleared --> Programmed: program_rp_ide_key
    Programmed --> Cleared: clear_rp_ide_key
    Programmed --> Enabled: set_go_rp_ide_key
    Enabled --> Programmed: set_stop_rp_ide_key

    Enabled --> Cleared: IDE stream Insecure
    Programmed --> Cleared: IDE stream Insecure
....

The possible error codes returned in `sbiret.error` are shown below.

[#table_sbi_covt_rp_ide_key_status]
.CoVE TSM PCIe Root Port IDE Key Status
[cols="2,3", width=90%, align="center", options="header"]
|===
| Error code              | Description
| SBI_SUCCESS             | The operation completed successfully.
| SBI_ERR_INVALID_PARAM   | `key_desc` or `rp_id` is invalid.
| SBI_ERR_FAILED          | The operation failed for unknown reasons.
|===
